const posts = [
  {
    id: 1,
    title: "Đánh bài",
    descriptions: "Những hạt gạo không hoàn hảo này đã bị loại bỏ theo truyền thống sau quá trình xay xát nhưng đã được nâng lên thành một nét văn hóa ẩm thực đường phố...",
    pic: "https://down-vn.img.susercontent.com/file/70eaa08af96969fe834f0181f9f832de",
    publishDate: "Sep 10, 2025",
    categoryId: "SaiGon",
    categoryName: "Ẩm thực Sài Gòn",
    paragraphs: [
      "Chơi bài tá lả, phỏm, tiến lên với mức bet siêu hấp dẫn.",
      "1 bộ bài sẽ giúp bạn healing.",
      "Hãy trải nghiệm workshop của chúng mình hoặc liên hệ 113 để được hướng dẫn nhé.",
      "thực sự rất đáng để bạn trải nghiệm.",
      "bạn có thể cầm đi mọi nơi",
      "trong khuân viên trường fpt.",
      "Nếu bạn đang gặp vấn đề về tâm lý hay stress bạn nên thử sản phẩm của chúng mình",
      "Một bộ bài có thể có giá từ 20.000 VND đến 60.000 VND ",
      "Có",
    ],
    headings: [
      "",
      "Sản phẩm chính của chúng mình là gì?",
      "Nguồn gốc từ đâu?",
      "Trải nghiệm như thế nào?",
      "Nó được phục vụ như thế nào?",
      "vị trí ở đâu ?",
      "Tại sao bạn nên thử nó?",
      "Giá cả?",
      "Bạn có thể làm nó ở nhà không?",
      "Nó có thể ảnh hưởng gì tới bạn",
    ],
    images: ["https://down-vn.img.susercontent.com/file/70eaa08af96969fe834f0181f9f832de"],
  },
  
   {
    id: 2,
    title: "Workshop offline",
    descriptions: "Workshop tại trường cho bạn nào muốn tham gia.",
    pic: "https://inedip.com/images/workshops.png",
    publishDate: "Sep 10, 2025",
    categoryId: "Offline",
    categoryName: "Workshop",
    headings: ["", "Workshop", "", "", "Exe201", ""],
    images: [
      "",
      "https://inedip.com/images/workshops.png",
      "",
      "",
      "https://inedip.com/images/workshops.png",
      "",
    ],
    paragraphs: [
      "đây là bài giới thiệu cho workshop.",
      "- Địa chỉ: Tòa alpha fpt",
      "Với dự án tâm huyết của chúng mình, chúng mình mong các bạn có thể tham gia",
      "",
      "hihi hâha hô hô",
      "là người thấu hiểu cảm xúc của các bạn, mình sẽ đưa ra những phương pháp và lời khuyên hữu dụng nhát.",
    ],
  },

  {
    id: 3,
    title: "Workshop offline",
    descriptions: "Workshop tại trường cho bạn nào muốn tham gia.",
    pic: "https://inedip.com/images/workshops.png",
    publishDate: "Sep 10, 2025",
    categoryId: "Offline",
    categoryName: "Workshop",
    headings: ["", "Workshop", "", "", "Exe201", ""],
    images: [
      "",
      "https://inedip.com/images/workshops.png",
      "",
      "",
      "https://inedip.com/images/workshops.png",
      "",
    ],
    paragraphs: [
      "đây là bài giới thiệu cho workshop.",
      "- Địa chỉ: Tòa alpha fpt",
      "Với dự án tâm huyết của chúng mình, chúng mình mong các bạn có thể tham gia",
      "",
      "hihi hâha hô hô",
      "là người thấu hiểu cảm xúc của các bạn, mình sẽ đưa ra những phương pháp và lời khuyên hữu dụng nhát.",
    ],
  },
 
 {
    id: 4,
    title: "Workshop offline",
    descriptions: "Workshop tại trường cho bạn nào muốn tham gia.",
    pic: "https://inedip.com/images/workshops.png",
    publishDate: "Sep 10, 2025",
    categoryId: "Offline",
    categoryName: "Workshop",
    headings: ["", "Workshop", "", "", "Exe201", ""],
    images: [
      "",
      "https://inedip.com/images/workshops.png",
      "",
      "",
      "https://inedip.com/images/workshops.png",
      "",
    ],
    paragraphs: [
      "đây là bài giới thiệu cho workshop.",
      "- Địa chỉ: Tòa alpha fpt",
      "Với dự án tâm huyết của chúng mình, chúng mình mong các bạn có thể tham gia",
      "",
      "hihi hâha hô hô",
      "là người thấu hiểu cảm xúc của các bạn, mình sẽ đưa ra những phương pháp và lời khuyên hữu dụng nhát.",
    ],
  },

];

export default posts;
